# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Amnesty.io
tagline:          Amnesty International Digital
url:              http://amnesty.io
paginate:         3
baseurl:          /
author:
  name:           Jackson Couse
  url:            https://twitter.com/jacksoncouse
  email:          jackson@jacksoncouse.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/amnestyinternational.github.io
